# Generated by Django 5.2.5 on 2025-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('google_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.JSONField(default=list)),
                ('published_date', models.CharField(blank=True, max_length=20, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
